// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_VIs7cMAZxWEEIU-J-JSFSPRXd9qArnQ',
    appId: '1:861838681926:android:1a694c134ec4960f4da747',
    messagingSenderId: '861838681926',
    projectId: 'remote-order-v1',
    storageBucket: 'remote-order-v1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtE6QPblDKRBu2om6o3rNECo_Blpt0y08',
    appId: '1:861838681926:ios:91e1253e0103c28b4da747',
    messagingSenderId: '861838681926',
    projectId: 'remote-order-v1',
    storageBucket: 'remote-order-v1.appspot.com',
    iosBundleId: 'com.felipecastrosales.remoteOrder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtE6QPblDKRBu2om6o3rNECo_Blpt0y08',
    appId: '1:861838681926:ios:bf671b1931a152644da747',
    messagingSenderId: '861838681926',
    projectId: 'remote-order-v1',
    storageBucket: 'remote-order-v1.appspot.com',
    iosBundleId: 'com.felipecastrosales.remoteOrder.RunnerTests',
  );
}
